# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audioStream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='audioStream.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x61udioStream.proto\"\x18\n\x07Samples\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"\x18\n\x08Response\x12\x0c\n\x04word\x18\x01 \x01(\t2<\n\x0e\x41udioProcessor\x12*\n\x0ftranscriptAudio\x12\x08.Samples\x1a\t.Response(\x01\x30\x01\x62\x06proto3')
)




_SAMPLES = _descriptor.Descriptor(
  name='Samples',
  full_name='Samples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='Samples.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=45,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='Response.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['Samples'] = _SAMPLES
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Samples = _reflection.GeneratedProtocolMessageType('Samples', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLES,
  __module__ = 'audioStream_pb2'
  # @@protoc_insertion_point(class_scope:Samples)
  ))
_sym_db.RegisterMessage(Samples)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'audioStream_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)



_AUDIOPROCESSOR = _descriptor.ServiceDescriptor(
  name='AudioProcessor',
  full_name='AudioProcessor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=73,
  serialized_end=133,
  methods=[
  _descriptor.MethodDescriptor(
    name='transcriptAudio',
    full_name='AudioProcessor.transcriptAudio',
    index=0,
    containing_service=None,
    input_type=_SAMPLES,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUDIOPROCESSOR)

DESCRIPTOR.services_by_name['AudioProcessor'] = _AUDIOPROCESSOR

# @@protoc_insertion_point(module_scope)
